### ISSUE TITLE
file box related issue

### ISSUE THREAD

**Issue by stefan38** [suewonjp/civilizer#5]
Hi,
After opening any selected file inside File Box and then trying to move them into another folder inside File Box an error message appears which says that the deletion of the original file after moving it to the newer location was impossible. The copy process is also not done. The desired operation can be done only after closing and restarting the Civilizer server. Thanks.

**Comment by suewonjp** [comment]
I couldn't reproduce the issue on Mac OS X.

But I could reproduce the issue on Windows 8.1 only on a special case.
When I opened a zip file from File Box and when I tried to delete the file while my zip application is still holding that file, I couldn't delete it. ( This is a normal behavior for Windows. )

On Windows, for example, you open a .docx file with MS word from the browser, and you try to delete the file while still the MS word running (sometimes you may not notice it is still running...), and then the file can't be deleted or moved. Also this behavior may differ depending on your Windows version. I could still move a file on Windows 8.1, but it wouldn't let me delete the same file. Other Windows version even may not let you move files...

Even though, say, you properly terminated the app, but you couldn't still move the file. However, If that's an application issue, it should happen on other platforms like Mac OS X.

> The desired operation can be done only after closing and restarting the Civilizer server

This is what I can't explain about. Sorry...

Well, Civilizer doesn't do any special operations in terms of moving or deleting files. It just asks OS to do that. 

What I can tell for now is that this seems like an OS related issue and Civilizer can't do much about it... or more evidences are required to show that it was actually an application issue.
